# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="theunraveler"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

plugins=(git osx)

set -k
setopt rcquotes

export EDITOR='vim'

source $ZSH/oh-my-zsh.sh

source "$HOME/.zsh/aliases.zsh"
source "$HOME/.zsh/exports.zsh"
